name: Build and Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Code Quality Check
        run: dotnet format CA3_WebApp.csproj --verify-no-changes

      - name: Build webapp
        run: dotnet build CA3_WebApp.csproj --configuration Release

      - name: Publish webapp
        run: dotnet publish CA3_WebApp.csproj -c Release -o build

      - name: Rewrite base href # overrite base href in index.html so that deployed version base ref matches 
        run: sed -i 's|<base href="/" />|<base href="/CA3_WebApp_X00203931/" />|' build/wwwroot/index.html

      - name: Install Playwright
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Build E2E Test Project
        run: dotnet build CA3_E2E_Tests/CA3_E2E_Tests.csproj --configuration Release

      - name: Install Playwright Browsers
        working-directory: CA3_E2E_Tests
        run: playwright install --with-deps

      - name: Run E2E Tests
        run: dotnet test CA3_E2E_Tests/CA3_E2E_Tests.csproj --configuration Release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/wwwroot
          branch: gh-pages
